#!/usr/bin/env Rscript
# Generic runner:  Rscript sim_rerun/run_block.R <block ...>   (0 = lambda diag)
suppressWarnings(suppressMessages({
  source("sim_rerun/R/common.R")
  source("sim_rerun/R/config.R")
  source("sim_rerun/R/engine2.R")
  for (b in 1:5) source(sprintf("sim_rerun/R/block%d.R", b))
  source("sim_rerun/R/lambda_diag.R")
  source("sim_rerun/R/verdict.R")
}))
args   <- commandArgs(trailingOnly = TRUE)
blocks <- if (length(args)) as.integer(args) else c(1L, 0L, 2:5)
t_start <- proc.time()
if (1L %in% blocks) run_block1()
if (0L %in% blocks) run_lambda_diag()
if (2L %in% blocks) run_block2()
if (3L %in% blocks) run_block3()
if (4L %in% blocks) run_block4()
if (5L %in% blocks) run_block5()
run_verdict()
cat(sprintf("\nTotal wall time: %.1f min\n", (proc.time() - t_start)[3] / 60))
